# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_secret', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=60)),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='permissions',
            field=models.ManyToManyField(to='clients.Permission'),
        ),
    ]
