# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='clients.Permission'),
        ),
    ]
