# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170524_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
